version: '2'
services:
  node1:
    image: cassandra:{{ cassandra_version }}
    mem_limit: 512m
    cpu_shares: 20
    volumes:
     - ./node1:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "{{ cassandra_seeds }}"
      CASSANDRA_LISTEN_ADDRESS: "{{ node1 }}"
      CASSANDRA_BROADCAST_ADDRESS: "{{ node1 }}"
      CASSANDRA_RPC_ADDRESS: "{{ node1 }}"
    networks:
      cassandra_net:
        ipv4_address: {{ node1 }}

  node2:
    image: cassandra:{{ cassandra_version }}
    mem_limit: 512m
    cpu_shares: 20
    volumes:
     - ./node2:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "{{ cassandra_seeds }}"
      CASSANDRA_LISTEN_ADDRESS: "{{ node2 }}"
      CASSANDRA_BROADCAST_ADDRESS: "{{ node2 }}"
      CASSANDRA_RPC_ADDRESS: "{{ node2 }}"
    networks:
      cassandra_net:
        ipv4_address: {{ node2 }}

  node3:
    image: cassandra:{{ cassandra_version }}
    mem_limit: 512m
    cpu_shares: 20
    volumes:
     - ./node3:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: "{{ cassandra_seeds }}"
      CASSANDRA_LISTEN_ADDRESS: {{ node3 }}
      CASSANDRA_BROADCAST_ADDRESS: "{{ node3 }}"
      CASSANDRA_RPC_ADDRESS: "{{ node3 }}"
    networks:
      cassandra_net:
        ipv4_address: {{ node3 }}

networks:
  cassandra_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.8.0/24
         gateway: 10.8.8.1
         